server:
  port: 8094

# DB 접속 정보
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootclass3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bootuser3
    password: 1234
  thymeleaf:
    cache: false

  # JSA 관련 설정 (처음에 ddl-auto를 create로 잡아주고 테이블 다만들고 건들게 없으면 update로 바꿔주자)
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update